name: example
description: Example project for form_builder_file_picker package
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.6.0
  form_builder_file_picker:
      path: ../

dev_dependencies:
  flutter_lints: ">=5.0.0 <6.0.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true