name: form_builder_file_picker
description: FilePicker Field for flutter_form_builder package. Used to select files as part of form input.
version: 5.0.0
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_file_picker
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_file_picker/issues
homepage: https://github.com/flutter-form-builder-ecosystem
topics:
  - form
funding: 
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  community_material_icon: ^5.9.55
  file_picker: ^10.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  flutter_lints: ">=5.0.0 <6.0.0"
  flutter_test:
    sdk: flutter
