name: form_builder_file_picker
description: FilePicker Field for flutter_form_builder package. Used to select files as part of form input.
version: 2.4.0
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_file_picker
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_file_picker/issues
funding: 
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  community_material_icon: ^5.9.55
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.8.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
