name: form_builder_file_picker
description: FilePicker Field for flutter_form_builder package. Used to select files as part of form input.
version: 4.0.0-dev.2
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_file_picker
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_file_picker/issues
homepage: https://github.com/flutter-form-builder-ecosystem
funding: 
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  community_material_icon: ^5.9.55
  file_picker: ^5.3.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
